from apps.views.auths import RegisterSmsCodeAPIView, RegisterAPIView, QRCodeLoginRequestView, QRCodeLoginAuthorizeView, QRCodeLoginStatusView
from apps.views.chats import UserChatRoomListAPIView, ChatHistoryListAPIView
from apps.views.products import ProductModelViewSet, CityListAPIView, DeliveryPointsListAPIView, DeliveryPointsRetrieveAPIView, CategoryListAPIView, FavoriteProductRetrieveAPIView, FavoriteProductListCreateAPIView, ShopRetrieveUpdateDestroyAPIView, ShopListCreateAPIView, CommentListAPIView, CommentCreateAPIView
